class MaintenanceRequest < ApplicationRecord
  include AASM

  belongs_to :room
  belongs_to :assignee, class_name: "User", optional: true

  enum :category, {
    plumbing: "plumbing",
    electrical: "electrical",
    hvac: "hvac",
    appliance: "appliance",
    furniture: "furniture",
    structural: "structural",
    other: "other"
  }

  enum :priority, {
    low: "low",
    medium: "medium",
    high: "high",
    urgent: "urgent"
  }

  validates :title, presence: true
  # A hand-crafted assignee_id for a missing user would otherwise hit the DB
  # foreign key and 500; turn it into a validation error at the model boundary.
  validate :assignee_must_exist, if: -> { assignee_id.present? }

  # Active requests still hold the room out of service; closing the last one
  # frees it. "active" = open or in_progress.
  scope :active, -> { where(status: %w[ open in_progress ]) }
  scope :active_for, ->(room) { active.where(room: room) }

  # AASM owns the status column directly (no Rails enum on it) — same pattern as
  # Reservation, to avoid two state machines fighting over one column. State
  # scopes (open, in_progress, ...) are generated by AASM.
  aasm column: :status do
    state :open, initial: true
    state :in_progress
    state :resolved
    state :cancelled

    event :start do
      transitions from: :open, to: :in_progress
    end

    event :resolve do
      transitions from: %i[ open in_progress ], to: :resolved
    end

    event :cancel do
      transitions from: %i[ open in_progress ], to: :cancelled
    end
  end

  private

  def assignee_must_exist
    errors.add(:assignee_id, :invalid) if assignee.nil?
  end
end
