class Reservation < ApplicationRecord
  include AASM

  belongs_to :guest
  belongs_to :room

  validates :check_in_on, :check_out_on, presence: true
  validates :nightly_rate_cents, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :internal_id, presence: true, uniqueness: true
  validate :check_out_after_check_in

  # Human-friendly reservation code, assigned on creation through every path
  # (BookRoom, factories). before_validation (not before_create) so the presence
  # + uniqueness validations see the generated value. Own-data only.
  before_validation :assign_internal_id, on: :create

  # AASM owns the status column directly — no Rails enum, to avoid two state
  # machines fighting over the same column. State scopes (booked, checked_in,
  # ...) are generated by AASM.
  aasm column: :status do
    state :booked, initial: true
    state :checked_in
    state :checked_out
    state :cancelled

    event :check_in do
      transitions from: :booked, to: :checked_in
    end

    event :check_out do
      transitions from: :checked_in, to: :checked_out
    end

    event :cancel do
      transitions from: :booked, to: :cancelled
    end
  end

  # Reservations that hold a room: booked or already in-house. Half-open overlap
  # so a stay ending the day another begins does not conflict.
  scope :overlapping, ->(period) {
    where(status: %w[ booked checked_in ])
      .where("check_in_on < ? AND ? < check_out_on", period.check_out, period.check_in)
  }
  scope :arriving_on, ->(date) { booked.where(check_in_on: date) }
  scope :departing_on, ->(date) { checked_in.where(check_out_on: date) }

  # List filters. Each is nil-safe so the console can apply them independently.
  scope :between_dates, ->(from, to) {
    rel = all
    rel = rel.where("check_out_on >= ?", from) if from.present?
    rel = rel.where("check_in_on <= ?", to) if to.present?
    rel
  }
  scope :with_status, ->(status) { where(status: status) }
  # Case-insensitive partial match on the reservation code.
  scope :with_code, ->(query) { where("internal_id LIKE ?", "%#{query.upcase}%") }

  # Composes the console list filters, skipping any that are blank.
  def self.filtered(date_from: nil, date_to: nil, status: nil, code: nil)
    scope = all
    scope = scope.with_code(code) if code.present?
    scope = scope.between_dates(date_from, date_to) if date_from.present? || date_to.present?
    scope = scope.with_status(status) if status.present?
    scope
  end

  def stay_period
    StayPeriod.new(check_in: check_in_on, check_out: check_out_on)
  end

  def total_cents
    nightly_rate_cents * stay_period.nights
  end

  private

  def assign_internal_id
    return if internal_id.present?

    self.internal_id = loop do
      code = ReservationCode.generate
      break code unless self.class.exists?(internal_id: code)
    end
  end

  def check_out_after_check_in
    return if check_in_on.blank? || check_out_on.blank?

    errors.add(:check_out_on, :after_check_in) if check_out_on <= check_in_on
  end
end
